# Handlers
handlers=java.util.logging.ConsoleHandler

# Console Handler configuration
java.util.logging.ConsoleHandler.level=ALL
java.util.logging.ConsoleHandler.formatter=br.cefetmg.lsi.l2l.common.CompactFormatter

# Default global logging level
.level=INFO

# Set debug level for your application packages
br.cefetmg.lsi.l2l.level=ALL
br.cefetmg.lsi.l2l.cluster.level=INFO
br.cefetmg.lsi.l2l.creature.level=ALL
br.cefetmg.lsi.l2l.physics.level=ALL
br.cefetmg.lsi.l2l.world.level=ALL
