# Handlers
handlers=java.util.logging.ConsoleHandler

# Console Handler configuration
java.util.logging.ConsoleHandler.level=ALL
java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter
java.util.logging.SimpleFormatter.format=%1$tY-%1$tm-%1$td %1$tH:%1$tM:%1$tS.%1$tL %4$-7s [%3$s] %5$s %6$s%n

# Default global logging level
.level=INFO

# Set debug level for your application packages
br.cefetmg.lsi.l2l.level=ALL
br.cefetmg.lsi.l2l.cluster.level=SEVERE
br.cefetmg.lsi.l2l.creature.level=ALL
br.cefetmg.lsi.l2l.physics.level=ALL
br.cefetmg.lsi.l2l.world.level=ALL
