version: "3.1"
services:
  dl2l-manager:
    environment:
      SIMULATION: "simulations/phase2_1node_10creature.conf"
  dl2l-detector:
    environment:
      SIMULATION: "simulations/phase2_1node_10creature.conf"
  dl2l-holder:
    environment:
      SIMULATION: "simulations/phase2_1node_10creature.conf"
