object-dispatcher {
  type = Dispatcher
  executor = "fork-join-executor"

  fork-join-executor {
    parallelism-min = 2
    parallelism-factor = 2.0
    parallelism-max = 20
  }
  throughput = 10
}

bd-dispatcher {
  type = PinnedDispatcher
  mailbox-type = "br.cefetmg.lsi.l2l.common.ComponentMailbox"
  executor = "thread-pool-executor"
}

wm-dispatcher {
  type = PinnedDispatcher
  executor = "thread-pool-executor"
  thread-pool-executor {
    fixed-pool-size = 1
  }
}

collision-dispatcher {
  mailbox-type = "br.cefetmg.lsi.l2l.cluster.CollisionDetectorPriorityMailbox"
}

component-dispatcher {
  mailbox-type = "br.cefetmg.lsi.l2l.common.ComponentMailbox"
}

akka.actor.deployment {
  "/holder/object-*" {
    dispatcher = object-dispatcher
  }
}


akka {
  loglevel = "DEBUG"

  actor {
    #provider = "akka.cluster.ClusterActorRefProvider"
    provider = "cluster"
    guardian-supervisor-strategy = "akka.actor.StoppingSupervisorStrategy"
  }
  remote {
    artery {
      enabled = false  # Since you're using classic remoting
    }
    netty.tcp {
      hostname = ${HOST}
      port = ${PORT}
      bind-hostname = ${HOST} #0.0.0.0 # Allow external connections
      bind-port = ${PORT}
    }
    log-remote-lifecycle-events = on
    use-passive-connections = off
  }

  cluster {
    seed-nodes = [
      "akka.tcp://l2l@dl2l-manager:2551",
    ]
    min-nr-of-members = 2
  }
  version = 2.5.32
}
