simulation {
  holders = 1
  positionFactory = "br.cefetmg.lsi.l2l.world.RandomPositionFactory"
  reposition = true

  creatureSettings = [{
    quantity = 10
  }]

  worldObjectSettings = [{
    objectType = "RED_APPLE"
    quantity = 285
  }, {
    objectType = "GREEN_APPLE"
    quantity = 285
  }, {
    objectType = "GRAY_APPLE"
    quantity = 285
  }]

  worldSize = {
    width = 8000, height = 6000
  }

  learningSettings {
    circadianEnabled     = true
    consolidationEnabled = false
    enabledFilters       = [TARGET_DISTANCE, AFFORDANCE, RANDOM]
  }
}
