simulation {
  holders = 1
  noUI = true
  positionFactory = "br.cefetmg.lsi.l2l.world.RandomPositionFactory"

  creatureSettings = [{
    quantity = 10
  }]

  worldObjectSettings = [{
    objectType = "RED_APPLE"
    quantity = 180
  }, {
    objectType = "GREEN_APPLE"
    quantity = 180
  }, {
    objectType = "GRAY_APPLE"
    quantity = 120
  }, {
    objectType = "ROTTEN_APPLE"
    quantity = 90
  }, {
    objectType = "CACTUS"
    quantity = 30
  }, {
    objectType = "ALOE"
    quantity = 30
  }]

  learningSettings {
    circadianEnabled     = true
    consolidationEnabled = false
    enabledFilters       = [TARGET_DISTANCE, AFFORDANCE, RANDOM]
  }
}
